name: CGoGN3_ST
# This is first test of CI.
on:
  push:
     branch:
       - CI_test

jobs:
  build-linux:
    name: CGoGN3
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: 'Package installations'
        shell: bash
        run: |
          sudo apt update
          sudo apt install libeigen3-dev libglfw3-dev libtinyxml2-dev zlib1g-dev
      - name: 'Trying to compile cgogn_3'
        run:  |
          mkdir Build
          cd Build
          cmake ..
          make -j 4