name: CGoGN3_ST
# This is first test of CI.
on:
  push:
     branch:
       - CI_test

jobs:
  # build-linux:
  #   name: 'On Linux'
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v1
  #     - name: 'Package installations'
  #       shell: bash
  #       run: |
  #         sudo apt update
  #         sudo apt install libeigen3-dev libglfw3-dev libtinyxml2-dev zlib1g-dev
  #     - name: 'Trying to compile cgogn_3'
  #       run:  |
  #         mkdir Build
  #         cd Build
  #         cmake ..
  #         cmake --build . --target cgogn_core

  build-windows:
    name: 'On Windows'
    runs-on: windows-latest
    steps:
      - name: wget
        uses: wei/wget@v1
          with:
            args: https://mycore.core-cloud.net/index.php/s/ZrdcynlC2rXxf7x/download -O vcpkg.zip
          run: 7z x ./vcpkg.zip
      - uses: actions/checkout@v1
        shell: pwsh
      - name: 'Trying to compile cgogn_3'
        run:  |
          mkdir Build
          cd Build
          cmake .. -DCMAKE_TOOLCHAIN_FILE=..\vcpkg\scripts\buildsystems\vcpkg.cmake
          cmake --build . --target cgogn_core

# name: CGoGN3_ST
# on:
#   push:
#      branch:
#        - CI_test
# jobs:
#   build:
#     runs-on: ${{matrix.config.os}}
#     strategy:
#       fail-fast: false
#       matrix:
#         config:
#         - {
#             os: ubuntu-latest,
#             install_deps: 'sudo apt update; sudo apt install libeigen3-dev libglfw3-dev libtinyxml2-dev zlib1g-dev',
#             cmake_cmd: 'cmake ..'
#           }
#         - {
#             os: windows-latest,
#             install_deps: 'git clone https://github.com/Microsoft/vcpkg.git; cd vcpkg; .\bootstrap-vcpkg.bat ; .\vcpkg integrate install; .\vcpkg install eigen3:x64-windows glfw3:x64-windows tinyxml2:x64-windows zlib:x64-windows:x64-windows; cd ..',
#             cmake_cmd: 'cmake -G ninja -DCMAKE_TOOLCHAIN_FILE=..\..\scripts\buildsystems\vcpkg.cmake ..'
#           }
#     steps:
#       - uses: actions/checkout@v1
#       - name: 'Package installations'
#           run: ${{matrix.config.install_deps}}
#       - name: 'Trying to compile cgogn_3'
#         run: |
#           mkdir Build
#           cd Build
#           ${{runner.cmake_cmd}}
#           cmake --build .