name: CGoGN3_ST
on:
  push:
     branch:
       - CI_test
jobs:
  build:
    runs-on: ${{matrix.config.os}}
    shell: ${{matrix.config.shell}}
    strategy:
      fail-fast: false
      matrix:
        config:
        - {
            os: ubuntu-latest,
            shell: bash,
            install_deps: 'sudo apt update; sudo apt install libeigen3-dev libglfw3-dev libtinyxml2-dev zlib1g-dev',
            cmake_cmd: 'cmake ..'
          }
        - {
            os: windows-latest,
            shell: pwsh,
            install_deps: 'git clone https://github.com/Microsoft/vcpkg.git; cd vcpkg; .\bootstrap-vcpkg.bat ; .\vcpkg integrate install; .\vcpkg install eigen3:x64-windows glfw3:x64-windows tinyxml2:x64-windows zlib:x64-windows:x64-windows; cd ..',
            cmake_cmd: 'cmake -G ninja -DCMAKE_TOOLCHAIN_FILE=..\..\scripts\buildsystems\vcpkg.cmake ..'
          }

      - name: 'Package installations'
        run: ${{ runner.install_deps}}
      - uses: actions/checkout@v1
      - name: 'Trying to compile cgogn_3'
        run: |
          mkdir Build
          cd Build
          ${{runner.cmake_cmd}}
          cmake --build .